name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
         echo "HOST=${{ secrets.SSH_HOST }}"
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 3333 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on server
        run: |
          ssh -p 3333 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/projects/watering-client
            git pull origin master
            docker compose down
            docker compose up --build -d
          EOF